server:
  port: 8081
  error:
    include-message: always

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/banking_db
    username: root
    password: root_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
